//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int PK { get; set; }
        public string ActivityStatus { get; set; }
        public string ActivityName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> FK_ExecutedBy { get; set; }
        public Nullable<int> FK_ControledBy { get; set; }
        public int FK_TaskLog { get; set; }
        public Nullable<System.Guid> FK_WFInstanceID { get; set; }
        public string ActivityID { get; set; }
    
        public virtual User Handler_User { get; set; }
        public virtual User Controler_User { get; set; }
        public virtual WFInstancesLog WFInstancesLogItems { get; set; }
    }
}
