//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBManaEntities : DbContext
    {
        public DBManaEntities()
            : base("name=DBManaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> MANA_ActivityLog { get; set; }
        public virtual DbSet<User> MANA_User { get; set; }
        public virtual DbSet<InstancesTable> InstancesTable { get; set; }
        public virtual DbSet<WFInstancesLog> MANA_WFInstancesLog { get; set; }
        public virtual DbSet<WorkflowRepository> MANA_WorkflowRepository { get; set; }
        public virtual DbSet<Dossier> MANA_Dossier { get; set; }
    }
}
