//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Handler_ActivityLogItems = new HashSet<ActivityLog>();
            this.Controler_ActivityLogItems = new HashSet<ActivityLog>();
            this.Handled_WFInstancesLogItems = new HashSet<WFInstancesLog>();
            this.Controlled_WFInstancesLogItems = new HashSet<WFInstancesLog>();
        }
    
        public int PK { get; set; }
        public string Name { get; set; }
        public string UserID { get; set; }
    
        public virtual ICollection<ActivityLog> Handler_ActivityLogItems { get; set; }
        public virtual ICollection<ActivityLog> Controler_ActivityLogItems { get; set; }
        public virtual ICollection<WFInstancesLog> Handled_WFInstancesLogItems { get; set; }
        public virtual ICollection<WFInstancesLog> Controlled_WFInstancesLogItems { get; set; }
    }
}
