//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowRepository
    {
        public WorkflowRepository()
        {
            this.WFInstancesLogItems = new HashSet<WFInstancesLog>();
        }
    
        public int PK { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime ValidityStartDate { get; set; }
        public System.DateTime ValidityEndDate { get; set; }
        public string WorkFlow { get; set; }
        public string Area { get; set; }
        public string Function { get; set; }
    
        public virtual ICollection<WFInstancesLog> WFInstancesLogItems { get; set; }
    }
}
